language: java
jdk:
- oraclejdk8
script: mvn -V -e -B clean verify
after_success: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: cp .travis.settings.xml $HOME/.m2/settings.xml && mvn -e -B compile site-deploy
  skip_cleanup: true
  on:
    branch: master
cache:
  directories:
  - $HOME/.m2/repository
